const SessionConstants = {
  USER_FAILED: 'USER_FAILED',
  USER_SUCCESS: 'USER_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_FAILED: 'LOGOUT_FAILED',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS'
};

export default SessionConstants;
