export const UserConstant = {
  CURRENT_USER: 'CURRENT_USER',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_LOGIN_ERROR: 'USER_LOGIN_ERROR',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGOUT_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGOUT_ERROR: 'USER_LOGOUT_ERROR',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_ERROR: 'REGISTER_ERROR'
};;
